title: Physics World Model
description: An open, on-chain agent science platform
url: "https://physicsworldmodel.github.io"
baseurl: ""
theme: minima
permalink: pretty

minima:
  skin: auto

header_pages:
  - blog.md
  - whitepaper.md
  - about.md
